DEBUG := n
TARGET :=  hardware/i2c-algo-hermon.ko hardware/i2c-hermon.ko
OBJS   :=  hardware/i2c-algo-hermon.o hardware/i2c-hermon.o
# CFLAGS += -DI2C_BUS_RECOVERY
include $(PROJDIR)/development/opensource/firmware/drivers/i2c/core/Makefile.core
