#! /bin/sh
# /etc/init.d/fdserver: start FD Server
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

PATHFUL_FDSERVER=/usr/local/bin/fdserver
USB_DRIVERNAME=usbe


test -f /usr/local/bin/fdserver || exit 0


# Options for start/restart the daemons
#


#


case "$1" in
  start)
	lsmod | grep $USB_DRIVERNAME >/dev/null
	if [ $? == 1 ]
    then
  	  echo -n "Loading USB driver... "
	  insmod $USB_DRIVERNAME
	  echo "Done"
	fi
    echo -n "Starting FD Redirection Server: fdserver"
    start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
    echo "."
    ;;
  stop)
    echo -n "Stopping FD Redirection Server: fdserver"
    start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER
    echo "."
    ;;
    reload)
	echo -n "Reloading FD Redirection Server: fdserver"
	start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER --signal 1
	echo "."
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting FD Redirection Server: fdserver"
	start-stop-daemon --stop --quiet --retry 5 --oknodo --exec $PATHFUL_FDSERVER
	start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/fdserver {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
