#SUBDIRS = 
#
#all: subdirs
#
#subdirs:
#	for n in $(SUBDIRS); do $(MAKE) -C $$n all|| exit 1; done
#
#install:
#	for n in $(SUBDIRS); do $(MAKE) -C $$n install || exit 1; done
#
#clean:
#	for n in $(SUBDIRS); do $(MAKE) -C $$n clean; done
#
#lint:
#	for n in $(SUBDIRS); do $(MAKE) -C $$n lint; done
#

all:

subdirs:

install:

clean:

lint:


