#!/bin/sh
# /etc/init.d/adviserd: start video Server
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
VIDEOSERVER_PATH="/usr/local/bin/"
VIDEOSERVER_STOP_CMD="killall"
VIDEOSERVER_NAME="videod"

VIDEO_DRIVERNAME=videocap

case "$1" in
start)
    	lsmod | grep $VIDEO_DRIVERNAME >/dev/null
	if [ $? == 1 ]
        then
  		echo -n "Loading Video capture driver... "
	       	insmod $VIDEO_DRIVERNAME
	       	echo "Done"
	fi
	echo -n "Starting Video Redirection Server : videod"
    	start-stop-daemon --start --quiet --exec $VIDEOSERVER_PATH$VIDEOSERVER_NAME &
	echo "."
	echo -n
	;;
stop)
	echo -n "Stopping Video Redirection Server: videod"
    	start-stop-daemon --stop --quiet --exec $VIDEOSERVER_PATH$VIDEOSERVER_NAME
	echo "."
	echo -n
	;;
*)
	echo "Usage: /etc/init.d/adviserd -p <portno> {start|stop}"
   	echo " if port is not given, then default port <7578> will be used"
   	echo "."
   	echo -n
	exit 1
esac
exit 0
