#!/bin/sh
# /etc/init.d/adviserd: start Adviserd
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

PATHFUL_ADVISER=/usr/local/bin/Adviserd
PATH_STUNNEL=/usr/sbin/stunnel4
PATHFUL_CDSERVER=/usr/local/bin/cdserver
PATHFUL_FDSERVER=/usr/local/bin/fdserver

test -f /usr/local/bin/Adviserd || exit 0
test -f /usr/local/bin/fdserver || exit 0
test -f /usr/local/bin/cdserver || exit 0


# Options for start/restart the daemons
#


#


case "$1" in
  start)
    echo -n "Starting Adviser :Adviserd"
    start-stop-daemon --start --quiet --exec $PATHFUL_ADVISER
    echo "."
    ;;
  stop)
    echo -n "Stopping Adviser :Adviserd"
    start-stop-daemon --stop --quiet --exec $PATHFUL_ADVISER
	start-stop-daemon --stop --quiet --exec $PATHFUL_CDSERVER
	start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER
    sleep 5
    start-stop-daemon --stop --quiet --exec $PATH_STUNNEL
    start-stop-daemon --stop --quiet --exec $PATHFUL_ADVISER --signal KILL
    start-stop-daemon --stop --quiet --exec $PATH_STUNNEL --signal KILL
	start-stop-daemon --stop --quiet --exec $PATHFUL_CDSERVER --signal KILL
	start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER --signal KILL
    echo "."
    ;;
    reload)
	echo -n "Reloading Adviser :Adviserd"
    	start-stop-daemon --stop --quiet --exec $PATHFUL_ADVISER
	sleep 5
	start-stop-daemon --stop --quiet --exec $PATHFUL_ADVISER --signal KILL
	#start-stop-daemon --stop --quiet --exec $PATHFUL_ADVISER --signal 1
	echo "."
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting Adviser :Adviserd"
    	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_ADVISER
		start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_CDSERVER
		start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_FDSERVER
	sleep 5
	start-stop-daemon --stop --quiet --exec $PATH_STUNNEL
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_ADVISER --signal KILL
	start-stop-daemon --stop --quiet --exec $PATH_STUNNEL --signal KILL
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_CDSERVER --signal KILL
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_FDSERVER --signal KILL
	
	# Now start again
	start-stop-daemon --start --quiet --exec $PATHFUL_ADVISER
	start-stop-daemon --start --quiet --exec $PATHFUL_CDSERVER
	start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/cdserver {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
