#!/bin/sh
# /etc/init.d/videod: start video Server
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

PATHFUL_IPMIINIT="/usr/local/bin/IPMIMain"



test -f /usr/local/bin/IPMIMain || exit 0


# Options for start/restart the daemons
#


#


case "$1" in
  start)
    echo -n "Starting IPMI Stack: IPMIMain "
    #we just do ldconfig since ipmi may be started very early on
    # Run ldconfig - Ractrends Specific  
    if [ -x /sbin/ldconfig ] 
    then 
	echo "Creating /var/ld.so.cache to which /etc/ld.so.cache is linked..."
	/sbin/ldconfig -C /var/ld.so.cache
    fi
    /usr/local/bin/IPMIMain &
#    start-stop-daemon --start --quiet --exec $PATHFUL_IPMIINIT
    echo "."
    ;;
  stop)
    echo -n "Stopping IPMI Stack: IPMIMain"
    killall IPMIMain
#    start-stop-daemon --stop --quiet --exec $PATHFUL_IPMIINIT
    echo "."
    ;;
    reload)
	echo -n "Reloading IPMI Stack: IPMIMain"
	echo "dont know what to do with reload right now"
#	start-stop-daemon --stop --quiet --exec $PATHFUL_IPMIINIT --signal 1
	echo "."
	;;
    force-reload)
#	$0 reload
	;;
    restart)
	echo -n "Restarting IPMI Stack: IPMIMain"
	killall IPMIMain
	/usr/local/bin/IPMIMain &
#	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_IPMIINIT
#	start-stop-daemon --start --quiet --exec $PATHFUL_IPMIINIT
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/ipmistack {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
