#!/bin/sh
# /etc/init.d/adviserd: start Adviserd
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

PATH_STUNNEL=/usr/sbin/stunnelvm
STUNNEL_VM_CFG=/conf/stunnel_vmedia.conf
STUNNEL_VM_NAME=stunnelvm
PATHFUL_CDSERVER=/usr/local/bin/cdserver
PATHFUL_FDSERVER=/usr/local/bin/fdserver

USB_DRIVERNAME=usbe

test -f /usr/local/bin/fdserver || exit 0
test -f /usr/local/bin/cdserver || exit 0
test -f /usr/sbin/stunnelvm || exit 0


# Options for start/restart the daemons
#


#


case "$1" in
  start)
	lsmod | grep $USB_DRIVERNAME >/dev/null
	if [ $? == 1 ]
    then
  	  echo -n "Loading USB driver... "
	  insmod $USB_DRIVERNAME
	  echo "Done"
	fi

    echo -n "Starting VMedia servers"
    start-stop-daemon --start --quiet --exec $PATHFUL_CDSERVER
    start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
    start-stop-daemon --start --quiet -n $STUNNEL_VM_NAME --exec $PATH_STUNNEL -- $STUNNEL_VM_CFG
    echo "."
    ;;
  stop)
    echo -n "Stopping VMedia servers"
    start-stop-daemon --stop --quiet --exec $PATHFUL_CDSERVER
    start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER
    start-stop-daemon --stop --quiet --exec $PATH_STUNNEL -n $STUNNEL_VM_NAME
    sleep 3
    start-stop-daemon --stop --quiet --exec $PATH_STUNNEL -n $STUNNEL_VM_NAME --signal KILL
    start-stop-daemon --stop --quiet --exec $PATHFUL_CDSERVER --signal KILL
    start-stop-daemon --stop --quiet --exec $PATHFUL_FDSERVER --signal KILL
    echo "."
    ;;
    reload)
	$0 restart
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting VMedia servers"
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_CDSERVER
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_FDSERVER
	start-stop-daemon --stop --quiet --exec $PATH_STUNNEL -n $STUNNEL_VM_NAME
	sleep 5
	start-stop-daemon --stop --quiet --exec $PATH_STUNNEL -n $STUNNEL_VM_NAME --signal KILL
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_CDSERVER --signal KILL
	start-stop-daemon --stop --quiet --oknodo --exec $PATHFUL_FDSERVER --signal KILL
	
	# Now start again
	start-stop-daemon --start --quiet --exec $PATHFUL_CDSERVER
	start-stop-daemon --start --quiet --exec $PATHFUL_FDSERVER
	start-stop-daemon --start --quiet -n $STUNNEL_VM_NAME --exec $PATH_STUNNEL -- $STUNNEL_VM_CFG
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/cdserver {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
