#!/bin/sh
# /etc/init.d/ncsi: Enable user specified ncsi port
#
# chkconfig: 2345 10 90
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
NCSIAPP_PATH="/usr/local/bin/"
NCSIAPP_NAME="ncsiapp"


if [ "$1" = "start" ]
	then
	echo "Enabling User Specified NCSI Port ..."
	$NCSIAPP_PATH$NCSIAPP_NAME 
fi
exit 0
