#! /bin/sh
#
# chkconfig: 2345 23 23
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin

FLAGS="defaults 23"

test -f /usr/sbin/ntpd || exit 0

case "$1" in
	start)
		echo -n "Starting NTP server: ntpd"
  		start-stop-daemon --start --quiet --exec /usr/sbin/ntpd -- -l /dev/null
		echo "."
  		;;
	stop)
		echo -n "Stopping NTP server: ntpd"
  		start-stop-daemon --stop --quiet --signal TERM --exec /usr/sbin/ntpd
  		
# Sometimes one of the ntpd process are not stopped.So issue one more stop
  		start-stop-daemon --stop --quiet --signal TERM --exec /usr/sbin/ntpd
		echo "."
  		;;
	restart|force-reload)
		echo -n "Restarting NTP server: ntpd... "
  		start-stop-daemon --stop --quiet --exec /usr/sbin/ntpd
  		sleep 2
  		start-stop-daemon --start --quiet --exec /usr/sbin/ntpd
		echo "done."
  		;;
	*)
  		echo "Usage: /etc/init.d/ntp {start|stop|restart|force-reload}"
  		exit 1
		;;
esac

exit 0
