#!/bin/sh
# /etc/init.d/sshd: secure shell
#
# chkconfig: 2345 25 25
#
APP_NAME=sshd


PATH=/bin:/usr/bin:/sbin:/usr/sbin

APP_PATH=/usr/local/bin/$APP_NAME


test -f /usr/local/bin/$APP_NAME || exit 0


# Options for start/restart the daemons
#


#


case "$1" in
  start)
    echo -n "Starting Secure Shell Daemons : $APP_NAME"
    start-stop-daemon --start --quiet --exec $APP_PATH
    echo "."
    ;;
  stop)
    echo -n "Stopping Secure Shell Daemons : $APP_NAME"
    start-stop-daemon --stop --quiet --exec $APP_PATH
    echo "."
    ;;
    reload)
	echo -n "Reloading Secure Shell Daemons : $APP_NAME"
	start-stop-daemon --stop --quiet --exec $APP_PATH --signal 1
	echo "."
	;;
    force-reload)
	$0 reload
	;;
    restart)
	echo -n "Restarting Secure Shell Daemons: $APP_NAME"
	start-stop-daemon --stop --quiet --oknodo --exec $APP_PATH
	start-stop-daemon --start --quiet --exec $APP_PATH
	echo "."
	;;
   *)
    echo "Usage: /etc/init.d/$APP_NAME {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
